###################################################################

# Created by write_sdc on Sun May 11 17:04:06 2025

###################################################################
set sdc_version 2.0

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions -max WCCOM -max_library                               \
fsa0m_a_generic_core_ss1p62v125c\
                         -min BCCOM -min_library                               \
fsa0m_a_generic_core_ff1p98vm40c
set_max_area 0
set_load -pin_load 0.023353 [get_ports found]
set_load -pin_load 0.023353 [get_ports {N[52]}]
set_load -pin_load 0.023353 [get_ports {N[51]}]
set_load -pin_load 0.023353 [get_ports {N[50]}]
set_load -pin_load 0.023353 [get_ports {N[49]}]
set_load -pin_load 0.023353 [get_ports {N[48]}]
set_load -pin_load 0.023353 [get_ports {N[47]}]
set_load -pin_load 0.023353 [get_ports {N[46]}]
set_load -pin_load 0.023353 [get_ports {N[45]}]
set_load -pin_load 0.023353 [get_ports {N[44]}]
set_load -pin_load 0.023353 [get_ports {N[43]}]
set_load -pin_load 0.023353 [get_ports {N[42]}]
set_load -pin_load 0.023353 [get_ports {N[41]}]
set_load -pin_load 0.023353 [get_ports {N[40]}]
set_load -pin_load 0.023353 [get_ports {N[39]}]
set_load -pin_load 0.023353 [get_ports {N[38]}]
set_load -pin_load 0.023353 [get_ports {N[37]}]
set_load -pin_load 0.023353 [get_ports {N[36]}]
set_load -pin_load 0.023353 [get_ports {N[35]}]
set_load -pin_load 0.023353 [get_ports {N[34]}]
set_load -pin_load 0.023353 [get_ports {N[33]}]
set_load -pin_load 0.023353 [get_ports {N[32]}]
set_load -pin_load 0.023353 [get_ports {N[31]}]
set_load -pin_load 0.023353 [get_ports {N[30]}]
set_load -pin_load 0.023353 [get_ports {N[29]}]
set_load -pin_load 0.023353 [get_ports {N[28]}]
set_load -pin_load 0.023353 [get_ports {N[27]}]
set_load -pin_load 0.023353 [get_ports {N[26]}]
set_load -pin_load 0.023353 [get_ports {N[25]}]
set_load -pin_load 0.023353 [get_ports {N[24]}]
set_load -pin_load 0.023353 [get_ports {N[23]}]
set_load -pin_load 0.023353 [get_ports {N[22]}]
set_load -pin_load 0.023353 [get_ports {N[21]}]
set_load -pin_load 0.023353 [get_ports {N[20]}]
set_load -pin_load 0.023353 [get_ports {N[19]}]
set_load -pin_load 0.023353 [get_ports {N[18]}]
set_load -pin_load 0.023353 [get_ports {N[17]}]
set_load -pin_load 0.023353 [get_ports {N[16]}]
set_load -pin_load 0.023353 [get_ports {N[15]}]
set_load -pin_load 0.023353 [get_ports {N[14]}]
set_load -pin_load 0.023353 [get_ports {N[13]}]
set_load -pin_load 0.023353 [get_ports {N[12]}]
set_load -pin_load 0.023353 [get_ports {N[11]}]
set_load -pin_load 0.023353 [get_ports {N[10]}]
set_load -pin_load 0.023353 [get_ports {N[9]}]
set_load -pin_load 0.023353 [get_ports {N[8]}]
set_load -pin_load 0.023353 [get_ports {N[7]}]
set_load -pin_load 0.023353 [get_ports {N[6]}]
set_load -pin_load 0.023353 [get_ports {N[5]}]
set_load -pin_load 0.023353 [get_ports {N[4]}]
set_load -pin_load 0.023353 [get_ports {N[3]}]
set_load -pin_load 0.023353 [get_ports {N[2]}]
set_load -pin_load 0.023353 [get_ports {N[1]}]
set_load -pin_load 0.023353 [get_ports {N[0]}]
set_max_capacitance 0.5 [get_ports clk]
set_max_capacitance 0.5 [get_ports rst_n]
set_max_capacitance 0.5 [get_ports {W[68]}]
set_max_capacitance 0.5 [get_ports {W[67]}]
set_max_capacitance 0.5 [get_ports {W[66]}]
set_max_capacitance 0.5 [get_ports {W[65]}]
set_max_capacitance 0.5 [get_ports {W[64]}]
set_max_capacitance 0.5 [get_ports {W[63]}]
set_max_capacitance 0.5 [get_ports {W[62]}]
set_max_capacitance 0.5 [get_ports {W[61]}]
set_max_capacitance 0.5 [get_ports {W[60]}]
set_max_capacitance 0.5 [get_ports {W[59]}]
set_max_capacitance 0.5 [get_ports {W[58]}]
set_max_capacitance 0.5 [get_ports {W[57]}]
set_max_capacitance 0.5 [get_ports {W[56]}]
set_max_capacitance 0.5 [get_ports {W[55]}]
set_max_capacitance 0.5 [get_ports {W[54]}]
set_max_capacitance 0.5 [get_ports {W[53]}]
set_max_capacitance 0.5 [get_ports {W[52]}]
set_max_capacitance 0.5 [get_ports {W[51]}]
set_max_capacitance 0.5 [get_ports {W[50]}]
set_max_capacitance 0.5 [get_ports {W[49]}]
set_max_capacitance 0.5 [get_ports {W[48]}]
set_max_capacitance 0.5 [get_ports {W[47]}]
set_max_capacitance 0.5 [get_ports {W[46]}]
set_max_capacitance 0.5 [get_ports {W[45]}]
set_max_capacitance 0.5 [get_ports {W[44]}]
set_max_capacitance 0.5 [get_ports {W[43]}]
set_max_capacitance 0.5 [get_ports {W[42]}]
set_max_capacitance 0.5 [get_ports {W[41]}]
set_max_capacitance 0.5 [get_ports {W[40]}]
set_max_capacitance 0.5 [get_ports {W[39]}]
set_max_capacitance 0.5 [get_ports {W[38]}]
set_max_capacitance 0.5 [get_ports {W[37]}]
set_max_capacitance 0.5 [get_ports {W[36]}]
set_max_capacitance 0.5 [get_ports {W[35]}]
set_max_capacitance 0.5 [get_ports {W[34]}]
set_max_capacitance 0.5 [get_ports {W[33]}]
set_max_capacitance 0.5 [get_ports {W[32]}]
set_max_capacitance 0.5 [get_ports {W[31]}]
set_max_capacitance 0.5 [get_ports {W[30]}]
set_max_capacitance 0.5 [get_ports {W[29]}]
set_max_capacitance 0.5 [get_ports {W[28]}]
set_max_capacitance 0.5 [get_ports {W[27]}]
set_max_capacitance 0.5 [get_ports {W[26]}]
set_max_capacitance 0.5 [get_ports {W[25]}]
set_max_capacitance 0.5 [get_ports {W[24]}]
set_max_capacitance 0.5 [get_ports {W[23]}]
set_max_capacitance 0.5 [get_ports {W[22]}]
set_max_capacitance 0.5 [get_ports {W[21]}]
set_max_capacitance 0.5 [get_ports {W[20]}]
set_max_capacitance 0.5 [get_ports {W[19]}]
set_max_capacitance 0.5 [get_ports {W[18]}]
set_max_capacitance 0.5 [get_ports {W[17]}]
set_max_capacitance 0.5 [get_ports {W[16]}]
set_max_capacitance 0.5 [get_ports {W[15]}]
set_max_capacitance 0.5 [get_ports {W[14]}]
set_max_capacitance 0.5 [get_ports {W[13]}]
set_max_capacitance 0.5 [get_ports {W[12]}]
set_max_capacitance 0.5 [get_ports {W[11]}]
set_max_capacitance 0.5 [get_ports {W[10]}]
set_max_capacitance 0.5 [get_ports {W[9]}]
set_max_capacitance 0.5 [get_ports {W[8]}]
set_max_capacitance 0.5 [get_ports {W[7]}]
set_max_capacitance 0.5 [get_ports {W[6]}]
set_max_capacitance 0.5 [get_ports {W[5]}]
set_max_capacitance 0.5 [get_ports {W[4]}]
set_max_capacitance 0.5 [get_ports {W[3]}]
set_max_capacitance 0.5 [get_ports {W[2]}]
set_max_capacitance 0.5 [get_ports {W[1]}]
set_max_capacitance 0.5 [get_ports {W[0]}]
set_max_fanout 6 [get_ports clk]
set_max_fanout 6 [get_ports rst_n]
set_max_fanout 6 [get_ports {W[68]}]
set_max_fanout 6 [get_ports {W[67]}]
set_max_fanout 6 [get_ports {W[66]}]
set_max_fanout 6 [get_ports {W[65]}]
set_max_fanout 6 [get_ports {W[64]}]
set_max_fanout 6 [get_ports {W[63]}]
set_max_fanout 6 [get_ports {W[62]}]
set_max_fanout 6 [get_ports {W[61]}]
set_max_fanout 6 [get_ports {W[60]}]
set_max_fanout 6 [get_ports {W[59]}]
set_max_fanout 6 [get_ports {W[58]}]
set_max_fanout 6 [get_ports {W[57]}]
set_max_fanout 6 [get_ports {W[56]}]
set_max_fanout 6 [get_ports {W[55]}]
set_max_fanout 6 [get_ports {W[54]}]
set_max_fanout 6 [get_ports {W[53]}]
set_max_fanout 6 [get_ports {W[52]}]
set_max_fanout 6 [get_ports {W[51]}]
set_max_fanout 6 [get_ports {W[50]}]
set_max_fanout 6 [get_ports {W[49]}]
set_max_fanout 6 [get_ports {W[48]}]
set_max_fanout 6 [get_ports {W[47]}]
set_max_fanout 6 [get_ports {W[46]}]
set_max_fanout 6 [get_ports {W[45]}]
set_max_fanout 6 [get_ports {W[44]}]
set_max_fanout 6 [get_ports {W[43]}]
set_max_fanout 6 [get_ports {W[42]}]
set_max_fanout 6 [get_ports {W[41]}]
set_max_fanout 6 [get_ports {W[40]}]
set_max_fanout 6 [get_ports {W[39]}]
set_max_fanout 6 [get_ports {W[38]}]
set_max_fanout 6 [get_ports {W[37]}]
set_max_fanout 6 [get_ports {W[36]}]
set_max_fanout 6 [get_ports {W[35]}]
set_max_fanout 6 [get_ports {W[34]}]
set_max_fanout 6 [get_ports {W[33]}]
set_max_fanout 6 [get_ports {W[32]}]
set_max_fanout 6 [get_ports {W[31]}]
set_max_fanout 6 [get_ports {W[30]}]
set_max_fanout 6 [get_ports {W[29]}]
set_max_fanout 6 [get_ports {W[28]}]
set_max_fanout 6 [get_ports {W[27]}]
set_max_fanout 6 [get_ports {W[26]}]
set_max_fanout 6 [get_ports {W[25]}]
set_max_fanout 6 [get_ports {W[24]}]
set_max_fanout 6 [get_ports {W[23]}]
set_max_fanout 6 [get_ports {W[22]}]
set_max_fanout 6 [get_ports {W[21]}]
set_max_fanout 6 [get_ports {W[20]}]
set_max_fanout 6 [get_ports {W[19]}]
set_max_fanout 6 [get_ports {W[18]}]
set_max_fanout 6 [get_ports {W[17]}]
set_max_fanout 6 [get_ports {W[16]}]
set_max_fanout 6 [get_ports {W[15]}]
set_max_fanout 6 [get_ports {W[14]}]
set_max_fanout 6 [get_ports {W[13]}]
set_max_fanout 6 [get_ports {W[12]}]
set_max_fanout 6 [get_ports {W[11]}]
set_max_fanout 6 [get_ports {W[10]}]
set_max_fanout 6 [get_ports {W[9]}]
set_max_fanout 6 [get_ports {W[8]}]
set_max_fanout 6 [get_ports {W[7]}]
set_max_fanout 6 [get_ports {W[6]}]
set_max_fanout 6 [get_ports {W[5]}]
set_max_fanout 6 [get_ports {W[4]}]
set_max_fanout 6 [get_ports {W[3]}]
set_max_fanout 6 [get_ports {W[2]}]
set_max_fanout 6 [get_ports {W[1]}]
set_max_fanout 6 [get_ports {W[0]}]
set_max_transition 0.5 [get_ports clk]
set_max_transition 0.5 [get_ports rst_n]
set_max_transition 0.5 [get_ports {W[68]}]
set_max_transition 0.5 [get_ports {W[67]}]
set_max_transition 0.5 [get_ports {W[66]}]
set_max_transition 0.5 [get_ports {W[65]}]
set_max_transition 0.5 [get_ports {W[64]}]
set_max_transition 0.5 [get_ports {W[63]}]
set_max_transition 0.5 [get_ports {W[62]}]
set_max_transition 0.5 [get_ports {W[61]}]
set_max_transition 0.5 [get_ports {W[60]}]
set_max_transition 0.5 [get_ports {W[59]}]
set_max_transition 0.5 [get_ports {W[58]}]
set_max_transition 0.5 [get_ports {W[57]}]
set_max_transition 0.5 [get_ports {W[56]}]
set_max_transition 0.5 [get_ports {W[55]}]
set_max_transition 0.5 [get_ports {W[54]}]
set_max_transition 0.5 [get_ports {W[53]}]
set_max_transition 0.5 [get_ports {W[52]}]
set_max_transition 0.5 [get_ports {W[51]}]
set_max_transition 0.5 [get_ports {W[50]}]
set_max_transition 0.5 [get_ports {W[49]}]
set_max_transition 0.5 [get_ports {W[48]}]
set_max_transition 0.5 [get_ports {W[47]}]
set_max_transition 0.5 [get_ports {W[46]}]
set_max_transition 0.5 [get_ports {W[45]}]
set_max_transition 0.5 [get_ports {W[44]}]
set_max_transition 0.5 [get_ports {W[43]}]
set_max_transition 0.5 [get_ports {W[42]}]
set_max_transition 0.5 [get_ports {W[41]}]
set_max_transition 0.5 [get_ports {W[40]}]
set_max_transition 0.5 [get_ports {W[39]}]
set_max_transition 0.5 [get_ports {W[38]}]
set_max_transition 0.5 [get_ports {W[37]}]
set_max_transition 0.5 [get_ports {W[36]}]
set_max_transition 0.5 [get_ports {W[35]}]
set_max_transition 0.5 [get_ports {W[34]}]
set_max_transition 0.5 [get_ports {W[33]}]
set_max_transition 0.5 [get_ports {W[32]}]
set_max_transition 0.5 [get_ports {W[31]}]
set_max_transition 0.5 [get_ports {W[30]}]
set_max_transition 0.5 [get_ports {W[29]}]
set_max_transition 0.5 [get_ports {W[28]}]
set_max_transition 0.5 [get_ports {W[27]}]
set_max_transition 0.5 [get_ports {W[26]}]
set_max_transition 0.5 [get_ports {W[25]}]
set_max_transition 0.5 [get_ports {W[24]}]
set_max_transition 0.5 [get_ports {W[23]}]
set_max_transition 0.5 [get_ports {W[22]}]
set_max_transition 0.5 [get_ports {W[21]}]
set_max_transition 0.5 [get_ports {W[20]}]
set_max_transition 0.5 [get_ports {W[19]}]
set_max_transition 0.5 [get_ports {W[18]}]
set_max_transition 0.5 [get_ports {W[17]}]
set_max_transition 0.5 [get_ports {W[16]}]
set_max_transition 0.5 [get_ports {W[15]}]
set_max_transition 0.5 [get_ports {W[14]}]
set_max_transition 0.5 [get_ports {W[13]}]
set_max_transition 0.5 [get_ports {W[12]}]
set_max_transition 0.5 [get_ports {W[11]}]
set_max_transition 0.5 [get_ports {W[10]}]
set_max_transition 0.5 [get_ports {W[9]}]
set_max_transition 0.5 [get_ports {W[8]}]
set_max_transition 0.5 [get_ports {W[7]}]
set_max_transition 0.5 [get_ports {W[6]}]
set_max_transition 0.5 [get_ports {W[5]}]
set_max_transition 0.5 [get_ports {W[4]}]
set_max_transition 0.5 [get_ports {W[3]}]
set_max_transition 0.5 [get_ports {W[2]}]
set_max_transition 0.5 [get_ports {W[1]}]
set_max_transition 0.5 [get_ports {W[0]}]
set_ideal_network [get_ports clk]
set_ideal_network [get_ports rst_n]
create_clock [get_ports clk]  -period 60  -waveform {0 30}
set_clock_latency 1  [get_clocks clk]
set_clock_uncertainty 0.3  [get_clocks clk]
set_clock_transition -max -rise 0.1 [get_clocks clk]
set_clock_transition -max -fall 0.1 [get_clocks clk]
set_clock_transition -min -rise 0.1 [get_clocks clk]
set_clock_transition -min -fall 0.1 [get_clocks clk]
set_input_transition -max 0.5  [get_ports clk]
set_input_transition -min 0.5  [get_ports clk]
set_input_transition -max 0.5  [get_ports rst_n]
set_input_transition -min 0.5  [get_ports rst_n]
set_input_transition -max 0.5  [get_ports {W[68]}]
set_input_transition -min 0.5  [get_ports {W[68]}]
set_input_transition -max 0.5  [get_ports {W[67]}]
set_input_transition -min 0.5  [get_ports {W[67]}]
set_input_transition -max 0.5  [get_ports {W[66]}]
set_input_transition -min 0.5  [get_ports {W[66]}]
set_input_transition -max 0.5  [get_ports {W[65]}]
set_input_transition -min 0.5  [get_ports {W[65]}]
set_input_transition -max 0.5  [get_ports {W[64]}]
set_input_transition -min 0.5  [get_ports {W[64]}]
set_input_transition -max 0.5  [get_ports {W[63]}]
set_input_transition -min 0.5  [get_ports {W[63]}]
set_input_transition -max 0.5  [get_ports {W[62]}]
set_input_transition -min 0.5  [get_ports {W[62]}]
set_input_transition -max 0.5  [get_ports {W[61]}]
set_input_transition -min 0.5  [get_ports {W[61]}]
set_input_transition -max 0.5  [get_ports {W[60]}]
set_input_transition -min 0.5  [get_ports {W[60]}]
set_input_transition -max 0.5  [get_ports {W[59]}]
set_input_transition -min 0.5  [get_ports {W[59]}]
set_input_transition -max 0.5  [get_ports {W[58]}]
set_input_transition -min 0.5  [get_ports {W[58]}]
set_input_transition -max 0.5  [get_ports {W[57]}]
set_input_transition -min 0.5  [get_ports {W[57]}]
set_input_transition -max 0.5  [get_ports {W[56]}]
set_input_transition -min 0.5  [get_ports {W[56]}]
set_input_transition -max 0.5  [get_ports {W[55]}]
set_input_transition -min 0.5  [get_ports {W[55]}]
set_input_transition -max 0.5  [get_ports {W[54]}]
set_input_transition -min 0.5  [get_ports {W[54]}]
set_input_transition -max 0.5  [get_ports {W[53]}]
set_input_transition -min 0.5  [get_ports {W[53]}]
set_input_transition -max 0.5  [get_ports {W[52]}]
set_input_transition -min 0.5  [get_ports {W[52]}]
set_input_transition -max 0.5  [get_ports {W[51]}]
set_input_transition -min 0.5  [get_ports {W[51]}]
set_input_transition -max 0.5  [get_ports {W[50]}]
set_input_transition -min 0.5  [get_ports {W[50]}]
set_input_transition -max 0.5  [get_ports {W[49]}]
set_input_transition -min 0.5  [get_ports {W[49]}]
set_input_transition -max 0.5  [get_ports {W[48]}]
set_input_transition -min 0.5  [get_ports {W[48]}]
set_input_transition -max 0.5  [get_ports {W[47]}]
set_input_transition -min 0.5  [get_ports {W[47]}]
set_input_transition -max 0.5  [get_ports {W[46]}]
set_input_transition -min 0.5  [get_ports {W[46]}]
set_input_transition -max 0.5  [get_ports {W[45]}]
set_input_transition -min 0.5  [get_ports {W[45]}]
set_input_transition -max 0.5  [get_ports {W[44]}]
set_input_transition -min 0.5  [get_ports {W[44]}]
set_input_transition -max 0.5  [get_ports {W[43]}]
set_input_transition -min 0.5  [get_ports {W[43]}]
set_input_transition -max 0.5  [get_ports {W[42]}]
set_input_transition -min 0.5  [get_ports {W[42]}]
set_input_transition -max 0.5  [get_ports {W[41]}]
set_input_transition -min 0.5  [get_ports {W[41]}]
set_input_transition -max 0.5  [get_ports {W[40]}]
set_input_transition -min 0.5  [get_ports {W[40]}]
set_input_transition -max 0.5  [get_ports {W[39]}]
set_input_transition -min 0.5  [get_ports {W[39]}]
set_input_transition -max 0.5  [get_ports {W[38]}]
set_input_transition -min 0.5  [get_ports {W[38]}]
set_input_transition -max 0.5  [get_ports {W[37]}]
set_input_transition -min 0.5  [get_ports {W[37]}]
set_input_transition -max 0.5  [get_ports {W[36]}]
set_input_transition -min 0.5  [get_ports {W[36]}]
set_input_transition -max 0.5  [get_ports {W[35]}]
set_input_transition -min 0.5  [get_ports {W[35]}]
set_input_transition -max 0.5  [get_ports {W[34]}]
set_input_transition -min 0.5  [get_ports {W[34]}]
set_input_transition -max 0.5  [get_ports {W[33]}]
set_input_transition -min 0.5  [get_ports {W[33]}]
set_input_transition -max 0.5  [get_ports {W[32]}]
set_input_transition -min 0.5  [get_ports {W[32]}]
set_input_transition -max 0.5  [get_ports {W[31]}]
set_input_transition -min 0.5  [get_ports {W[31]}]
set_input_transition -max 0.5  [get_ports {W[30]}]
set_input_transition -min 0.5  [get_ports {W[30]}]
set_input_transition -max 0.5  [get_ports {W[29]}]
set_input_transition -min 0.5  [get_ports {W[29]}]
set_input_transition -max 0.5  [get_ports {W[28]}]
set_input_transition -min 0.5  [get_ports {W[28]}]
set_input_transition -max 0.5  [get_ports {W[27]}]
set_input_transition -min 0.5  [get_ports {W[27]}]
set_input_transition -max 0.5  [get_ports {W[26]}]
set_input_transition -min 0.5  [get_ports {W[26]}]
set_input_transition -max 0.5  [get_ports {W[25]}]
set_input_transition -min 0.5  [get_ports {W[25]}]
set_input_transition -max 0.5  [get_ports {W[24]}]
set_input_transition -min 0.5  [get_ports {W[24]}]
set_input_transition -max 0.5  [get_ports {W[23]}]
set_input_transition -min 0.5  [get_ports {W[23]}]
set_input_transition -max 0.5  [get_ports {W[22]}]
set_input_transition -min 0.5  [get_ports {W[22]}]
set_input_transition -max 0.5  [get_ports {W[21]}]
set_input_transition -min 0.5  [get_ports {W[21]}]
set_input_transition -max 0.5  [get_ports {W[20]}]
set_input_transition -min 0.5  [get_ports {W[20]}]
set_input_transition -max 0.5  [get_ports {W[19]}]
set_input_transition -min 0.5  [get_ports {W[19]}]
set_input_transition -max 0.5  [get_ports {W[18]}]
set_input_transition -min 0.5  [get_ports {W[18]}]
set_input_transition -max 0.5  [get_ports {W[17]}]
set_input_transition -min 0.5  [get_ports {W[17]}]
set_input_transition -max 0.5  [get_ports {W[16]}]
set_input_transition -min 0.5  [get_ports {W[16]}]
set_input_transition -max 0.5  [get_ports {W[15]}]
set_input_transition -min 0.5  [get_ports {W[15]}]
set_input_transition -max 0.5  [get_ports {W[14]}]
set_input_transition -min 0.5  [get_ports {W[14]}]
set_input_transition -max 0.5  [get_ports {W[13]}]
set_input_transition -min 0.5  [get_ports {W[13]}]
set_input_transition -max 0.5  [get_ports {W[12]}]
set_input_transition -min 0.5  [get_ports {W[12]}]
set_input_transition -max 0.5  [get_ports {W[11]}]
set_input_transition -min 0.5  [get_ports {W[11]}]
set_input_transition -max 0.5  [get_ports {W[10]}]
set_input_transition -min 0.5  [get_ports {W[10]}]
set_input_transition -max 0.5  [get_ports {W[9]}]
set_input_transition -min 0.5  [get_ports {W[9]}]
set_input_transition -max 0.5  [get_ports {W[8]}]
set_input_transition -min 0.5  [get_ports {W[8]}]
set_input_transition -max 0.5  [get_ports {W[7]}]
set_input_transition -min 0.5  [get_ports {W[7]}]
set_input_transition -max 0.5  [get_ports {W[6]}]
set_input_transition -min 0.5  [get_ports {W[6]}]
set_input_transition -max 0.5  [get_ports {W[5]}]
set_input_transition -min 0.5  [get_ports {W[5]}]
set_input_transition -max 0.5  [get_ports {W[4]}]
set_input_transition -min 0.5  [get_ports {W[4]}]
set_input_transition -max 0.5  [get_ports {W[3]}]
set_input_transition -min 0.5  [get_ports {W[3]}]
set_input_transition -max 0.5  [get_ports {W[2]}]
set_input_transition -min 0.5  [get_ports {W[2]}]
set_input_transition -max 0.5  [get_ports {W[1]}]
set_input_transition -min 0.5  [get_ports {W[1]}]
set_input_transition -max 0.5  [get_ports {W[0]}]
set_input_transition -min 0.5  [get_ports {W[0]}]
